language: python
python:
  - "3.7"
addons:
  mariadb: "10.2"
before_script:
  - pip install -r requirements.txt
  - mysql -u root -e "create user poss@localhost identified by 'poss';"
  - mysql -u root -e "create database poss;"
  - mysql -u root -e "grant all privileges on poss.* to poss@localhost;"
  - cp config.dist.py config.py
script: nosetests --all-modules --nocapture --where tests
