CREATE DATABASE `poss`;
CREATE USER 'poss'@'localhost' IDENTIFIED BY 'poss';
GRANT CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, ALTER, CREATE, CREATE VIEW, DELETE, DROP, INDEX, INSERT, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE, ALTER ROUTINE, EXECUTE ON `poss`.* TO 'poss'@'localhost';
