on: push
name: Build
jobs:
  docker-image:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@master
      - name: Docker Build
        run: |
          docker build -t "${{ github.repository }}/poss:${{ github.sha }}" .
      - name: Docker Login (docker.io)
        run: |
          docker login --username="${{ secrets.DOCKER_USERNAME }}" --password-stdin <<<"${{ secrets.DOCKER_PASSWORD }}"
        if: startsWith(github.event.ref, 'refs/tags/')
      - name: Docker Push (docker.io)
        run: |
          docker tag "${{ github.repository }}/poss:${{ github.sha }}" "docker.io/${{ github.repository }}:${GITHUB_REF#refs/*/}" && \
          docker push "docker.io/${{ github.repository }}:${GITHUB_REF#refs/*/}"
        if: startsWith(github.event.ref, 'refs/tags/')
      #- name: Docker Login (docker.pkg.github.com)
      #  run: |
      #    docker login --username="${{ secrets.GITHUB_DOCKER_USERNAME }}" --password-stdin docker.pkg.github.com <<<"${{ secrets.GITHUB_DOCKER_PASSWORD }}"
      #  if: startsWith(github.event.ref, 'refs/tags/')
      #- name: Docker Push (docker.pkg.github.com)
      #  run: |
      #    docker tag "${{ github.repository }}/poss:${{ github.sha }}" "docker.pkg.github.com/${{ github.repository }}/poss:${GITHUB_REF#refs/*/}" && \
      #    docker push "docker.pkg.github.com/${{ github.repository }}/poss:${GITHUB_REF#refs/*/}"
      #  if: startsWith(github.event.ref, 'refs/tags/')
